import { Link } from 'react-router-dom';
import { useDispatch, useSelector } from 'react-redux';
import { addToCart } from '../redux/cartSlice';
import { toggleWishlistItem } from '../redux/wishlistSlice';
import { useToast } from '../context/ToastContext';
import { getLocalizedCategoryName } from '../data/categoryCatalog';
import { useCurrency } from '../context/CurrencyContext';
import { useLocale } from '../context/LocaleContext';
function BestSellerCard({ product }) { const dispatch = useDispatch(); const { showToast } = useToast(); const isWishlisted = useSelector((state) => state.wishlist.items.some((item) => item.id === product.id)); const { formatPrice } = useCurrency(); const { t } = useLocale(); const handleAddToCart = () => { dispatch(addToCart(product)); showToast({ title: t('تمت الإضافة إلى السلة'), description: product.title, variant: 'success' }); }; const handleToggleWishlist = () => { dispatch(toggleWishlistItem(product)); showToast({ title: isWishlisted ? t('تمت الإزالة من المفضلة') : t('تم الحفظ في المفضلة'), description: product.title }); }; return <article className="group overflow-hidden bg-white transition duration-300 hover:shadow-[0_10px_28px_rgba(0,0,0,0.08)]"><div className="relative overflow-hidden bg-[#f5f5f5]"><Link to={`/product/${product.id}`} className="block aspect-[0.82] overflow-hidden"><img src={product.image} alt={product.title} className="h-full w-full object-contain transition duration-500 group-hover:scale-[1.03]" /></Link><button type="button" onClick={handleToggleWishlist} className={`absolute left-3 top-3 inline-flex h-9 w-9 items-center justify-center rounded-full border transition ${isWishlisted ? 'border-black bg-black text-white' : 'border-black/10 bg-white text-black'}`} aria-label={t('المفضلة')}>{isWishlisted ? '♥' : '♡'}</button></div><div className="p-3 text-right"><p className="text-[11px] text-black/55">{t(getLocalizedCategoryName(product.category))}</p><Link to={`/product/${product.id}`} className="mt-1 block line-clamp-2 min-h-[48px] text-sm leading-6 text-black hover:text-black/75">{product.title}</Link><div className="mt-2 flex items-center justify-between gap-2"><span className="text-sm font-semibold text-[#f56b00]">★ {product.rating.toFixed(1)}</span><p className="text-xl font-black text-black">{formatPrice(product.price)}</p></div><div className="mt-3 flex items-center justify-between gap-2"><button type="button" onClick={handleAddToCart} className="inline-flex h-9 items-center rounded-full border border-black/15 px-3 text-sm font-semibold text-black transition hover:bg-black hover:text-white">{t('أضف للسلة')}</button><Link to={`/product/${product.id}`} className="text-xs text-black/55 transition hover:text-black">{t('عرض التفاصيل')}</Link></div></div></article>; }
export default function BestSellersSection({ products }) { const { t } = useLocale(); return <section className="px-4 py-8 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1400px]"><div className="mb-5 flex items-end justify-between gap-4 border-b border-black/10 pb-3"><div className="text-right"><p className="text-sm font-semibold text-[#f56b00]">{t('الأفضل مبيعًا')}</p><h2 className="mt-1 text-2xl font-black text-black sm:text-3xl">{t('منتجات يفضّلها الزوار')}</h2></div><Link to="/category/new" className="text-sm font-medium text-black/65 transition hover:text-black">{t('عرض الكل')}</Link></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{products.map((product) => <BestSellerCard key={product.id} product={product} />)}</div></div></section>; }
